local tbText = {
	["USERNAME"] = "账号",
	["PASSWORD"] = "密码",
	["LOG_TIP_SAVE"] = "记住账号密码",
	["LOG_TIP_UNAME"] = "请输入账号",
	["LOG_TIP_PW"] = "请输入密码",
	["UNKNOWN_SERVER"] = "未知服务器",
	["REG_TIP_UNAME"] = "请输入账号",
	["REG_TIP_REGNAME"] = "请输入手机号或邮箱",
	["REG_TIP_PW"] = "请输入密码",
	["REG_TIP_PW2"] = "请再次输入密码",
	["ROL_TITLE"] = "请选择你的英雄",
	["TIP_EVIL"] = "积分",
	["NO_GUILD"] = "未加入公会",
	["C_ALL"] = "全部",
	["C_WORLD"] = "世界",
	["C_ROOM"] = "房间",
	["C_GUILD"] = "公会",
	["C_PRIVATE"] = "私聊",
	["C_LOG"] = "日志",
	["CHAT_TIP_ENTER"] = "输入聊天内容...",
	["INFO_TITLE"] = "信息",
	["VIDEO_TITLE"] = "回放",
	["VIDEO_TIP"] = "的录像回放",
	["SAVE_SUCCESS"] = "保存成功",
	["TIP_WELFARE"] = "每天可以领取一次公会奖励，公会金币资金越多、你的股份越多、奖励越丰富哦！",
	["GUILD_MASTER"] = "会长",
	["GUILD_NUM"] = "人数",
	["FUND"] = "资金",
	["GUILD_FUND"] = "公会资金",
	["MY_INVEST"] = "我的投资",
	["MY_STOCK"] = "我的股份",
	["TIP_NOT_ENOUGH_GOLD"] = "您的金币不足",
	["TIP_NOT_ENOUGH_CRYSTAL"] = "您的水晶不足",
	["CLIENT_VER"] = "客户端版本号",
	["TIP_DECK_NOT_FIT_HERO"] = "这张卡不适合你的英雄啊",
	["TIP_DECK_MORE_THAN_FOUR"] = "最多只能放4张相同的牌到牌堆",
	["TIP_WAIT_OPPONENT"] = "对方操作中，请耐心等待…",
}

return tbText

